import { StrictMode, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import { api, clearToken, formatMoney, formatNumber, login, tokenFor } from "./api";
import { AppShell, Card, EmptyState, LoginScreen, MetricCard, PageHeader, Pill, Skeleton, type NavItem } from "./components";
import { Icon, Logo } from "./icons";
import "./styles.css";

type Site = { id:string; name:string; address?:string; contact_phone?:string; plan?:string; license_status?:string; connection?:string; devices?:number; cameras_active?:number; cameras_expected?:number; days_left?:number; monthly_price_uzs?:number; last_seen?:string };
type DeviceMetric = { device_id:string; site_id:string; site_name?:string; label?:string; received_at?:string; cpu_percent?:number|null; ram_percent?:number|null; disk_percent?:number|null; fps?:number|null; inference_latency_ms?:number|null; uptime_sec?:number|null; npu_percent?:number|null };
type CreatedCustomer = {site_id:string;name:string;pairing_code:string;pairing_expires_at?:string;username:string;password:string};
type AdminInvoice = {id:string;site_name?:string;site_id:string;months:number;amount_uzs:number;state:string;provider?:string;created_at?:string;paid_at?:string};
type Feature = {code:string;name:string;category:string;monthly_usd_cents:number;cost_usd_cents:number;active?:boolean};
type AdminEvent = {event_id?:string;id?:string;event_type:string;label?:string;site_name?:string;camera_id?:string;occurred_at?:string};
type Account = {id:string;username:string;full_name?:string;role:string;status:string;company?:string;site_id?:string};
type ReadinessItem = {key:string;label:string;ok:boolean;required:boolean;reasons?:string[]};
type AdminDashboard = {
  range:string;
  stats:{ total_sites:number; active:number; total_devices:number; monthly_revenue_uzs:number; offline:number; not_paired:number; expiring_soon:number; by_connection?:Record<string,number> };
  sites:Site[];
  telemetry:DeviceMetric[];
  invoices?:{total?:number; pending?:number; paid?:number};
  readiness?:Record<string,unknown>;
  updated_at:string;
};

const NAV:NavItem[] = [
  {id:"overview",label:"Umumiy holat",icon:"home"},
  {id:"customers",label:"Mijozlar",icon:"users"},
  {id:"branches",label:"Filiallar",icon:"branch"},
  {id:"cameras",label:"Kameralar",icon:"camera"},
  {id:"devices",label:"Qurilmalar",icon:"server"},
  {id:"plans",label:"Tariflar",icon:"card"},
  {id:"payments",label:"To‘lovlar",icon:"invoice"},
  {id:"events",label:"AI hodisalar",icon:"pulse"},
  {id:"monitoring",label:"Monitoring",icon:"chart"},
  {id:"roles",label:"Rollar",icon:"shield"},
  {id:"settings",label:"Sozlamalar",icon:"settings"},
];

function useAdminDashboard(authenticated:boolean, range:string) {
  const [data,setData] = useState<AdminDashboard|null>(null); const [loading,setLoading] = useState(true); const [error,setError] = useState(""); const failures=useRef(0);
  const refresh = useCallback(async()=>{ if(!authenticated)return;try{const next=await api<AdminDashboard>(`/api/v1/admin/dashboard?range=${range}`,"admin");setData(next);setError("");failures.current=0;}catch(reason){failures.current+=1;setError(reason instanceof Error?reason.message:"Ma’lumot olinmadi");}finally{setLoading(false);}},[authenticated,range]);
  useEffect(()=>{let timer=0,stopped=false;const tick=async()=>{await refresh();if(!stopped)timer=window.setTimeout(tick,document.hidden?60_000:failures.current?30_000:15_000);};void tick();return()=>{stopped=true;window.clearTimeout(timer);};},[refresh]);
  return {data,loading,error,refresh};
}

function Percent({value}:{value:number|null|undefined}) { const safe=typeof value==="number"?Math.max(0,Math.min(value,100)):0;return <><div className="telemetry-head"><span>{typeof value==="number"?`${value.toFixed(1)}%`:"Yig‘ilmoqda"}</span></div><div className="progress"><span style={{width:`${safe}%`}}/></div></>; }

function SiteTable({sites,onCreate}:{sites:Site[];onCreate?:()=>void}) { return <Card><div className="card-head"><div><h2>Mijoz tizimlari</h2><p>Aloqa, tarif va kamera holati</p></div>{onCreate?<button className="btn btn-primary" onClick={onCreate}><Icon name="branch"/>Yangi mijoz</button>:null}</div>{sites.length?<div className="table-wrap"><table><thead><tr><th>Mijoz / filial</th><th>Aloqa</th><th>Kameralar</th><th>Tarif</th><th>To‘lov muddati</th></tr></thead><tbody>{sites.map(site=><tr key={site.id}><td><div className="table-title">{site.name}</div><div className="table-sub">{site.address||site.contact_phone||site.id}</div></td><td><Pill state={site.connection}>{site.connection==="online"?"Aloqada":site.connection==="stale"?"Eskirgan":site.connection==="not_paired"?"Ulanmagan":"Oflayn"}</Pill></td><td>{formatNumber(site.cameras_active)} / {formatNumber(site.cameras_expected)}</td><td>{site.plan||"—"}</td><td>{site.days_left==null?"—":`${site.days_left} kun`}</td></tr>)}</tbody></table></div>:<EmptyState icon="branch" title="Mijozlar yo‘q" detail="Yangi mijoz qo‘shilgach uning tizim holati shu yerda ko‘rinadi."/>}</Card>; }

function Telemetry({items}:{items:DeviceMetric[]}) { return <Card><div className="card-head"><div><h2>Qurilma telemetriyasi</h2><p>Haqiqiy heartbeat ma’lumotlari; mavjud bo‘lmagan ko‘rsatkich yashirilmaydi</p></div><Pill>{items.length} qurilma</Pill></div>{items.length?<div className="telemetry-grid">{items.map(item=><article className="telemetry" key={`${item.site_id}-${item.device_id}`}><div className="health-name" style={{marginBottom:15}}><div className="metric-icon tone-blue" style={{position:"static"}}><Icon name="server" size={18}/></div><div><b>{item.label||item.device_id}</b><small>{item.site_name||item.site_id}</small></div></div><div className="simple-row"><span>CPU</span><b>{item.cpu_percent==null?"—":`${item.cpu_percent.toFixed(1)}%`}</b></div><Percent value={item.cpu_percent}/><div className="simple-row"><span>RAM</span><b>{item.ram_percent==null?"—":`${item.ram_percent.toFixed(1)}%`}</b></div><Percent value={item.ram_percent}/><div className="simple-row"><span>Disk</span><b>{item.disk_percent==null?"—":`${item.disk_percent.toFixed(1)}%`}</b></div><Percent value={item.disk_percent}/><div className="simple-row"><span>FPS</span><b>{item.fps==null?"—":item.fps.toFixed(1)}</b></div><div className="simple-row"><span>Inference</span><b>{item.inference_latency_ms==null?"—":`${item.inference_latency_ms.toFixed(0)} ms`}</b></div>{item.npu_percent==null?null:<div className="simple-row"><span>NPU</span><b>{item.npu_percent.toFixed(1)}%</b></div>}</article>)}</div>:<EmptyState icon="server" title="Telemetriya yig‘ilmoqda" detail="Yangi agent heartbeat yuborgach CPU, RAM, disk, FPS va inference kechikishi ko‘rinadi."/>}</Card>; }

function Overview({data,onNavigate}:{data:AdminDashboard;onNavigate:(id:string)=>void}) { const s=data.stats; const problems=(s.offline||0)+(s.not_paired||0); return <><PageHeader title="Umumiy holat" subtitle="Platformadagi mijozlar, qurilmalar va daromadning joriy ko‘rinishi." actions={<button className="btn btn-primary" onClick={()=>onNavigate("customers")}><Icon name="users"/>Mijoz qo‘shish</button>}/>{problems?<div className="alert-strip alert-info"><Icon name="bell"/><div><strong>{problems} ta tizim e’tibor talab qiladi.</strong> {s.offline||0} ta oflayn, {s.not_paired||0} ta hali qurilmaga ulanmagan.</div></div>:null}<div className="metric-grid"><MetricCard label="Faol mijozlar" value={formatNumber(s.active)} note={`${formatNumber(s.total_sites)} ta jami`} icon="users" tone="blue"/><MetricCard label="Qurilmalar" value={formatNumber(s.total_devices)} note={`${formatNumber(s.offline)} ta oflayn`} icon="server" tone={s.offline?"red":"green"}/><MetricCard label="Oylik tushum" value={formatMoney(s.monthly_revenue_uzs)} note="Faol va grace obunalar" icon="invoice" tone="green"/><MetricCard label="Muddat yaqin" value={formatNumber(s.expiring_soon)} note="7 kun ichida" icon="bell" tone={s.expiring_soon?"yellow":"green"}/></div><div className="dashboard-grid"><div className="stack"><SiteTable sites={data.sites.slice(0,8)} onCreate={()=>onNavigate("customers")}/></div><div className="stack"><Card><div className="card-head"><div><h2>Aloqa taqsimoti</h2><p>Faol mijozlar bo‘yicha</p></div></div><div className="card-body">{Object.entries(s.by_connection||{}).map(([state,count])=><div className="simple-row" key={state}><span><Pill state={state}>{state}</Pill></span><b>{count}</b></div>)}</div></Card><Card><div className="card-head"><div><h2>Operatsion eslatma</h2><p>Navbatdagi ishlar</p></div></div><div className="simple-list"><div className="simple-row"><span>Ulanmagan qurilmalar</span><b>{s.not_paired||0}</b></div><div className="simple-row"><span>Oflayn mijozlar</span><b>{s.offline||0}</b></div><div className="simple-row"><span>Muddati yaqin</span><b>{s.expiring_soon||0}</b></div></div></Card></div></div></>; }

function CustomersPage({sites,onRefresh}:{sites:Site[];onRefresh:()=>Promise<void>}) {
  const[adding,setAdding]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[created,setCreated]=useState<CreatedCustomer|null>(null);
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;const values=new FormData(form);setBusy(true);setError("");setCreated(null);try{const site=await api<{site_id:string;name:string;pairing_code:string;pairing_expires_at?:string}>("/api/v1/admin/sites","admin",{method:"POST",body:JSON.stringify({name:String(values.get("name")||""),plan:String(values.get("plan")||"biznes"),subscription_months:Number(values.get("months")||1),contact_phone:String(values.get("phone")||"")||null,address:String(values.get("address")||"")||null})});const loginData=await api<{username:string;password:string}>(`/api/v1/admin/sites/${encodeURIComponent(site.site_id)}/login`,"admin",{method:"POST"});setCreated({...site,...loginData});form.reset();setAdding(false);await onRefresh();}catch(reason){setError(reason instanceof Error?reason.message:"Mijoz yaratilmadi");}finally{setBusy(false);}};
  const copyCredentials=()=>{if(!created)return;const text=`Chaqimchi AI\nPanel: ${window.location.origin}/owner\nLogin: ${created.username}\nParol: ${created.password}\nQurilma kodi: ${created.pairing_code}`;void navigator.clipboard?.writeText(text);};
  return <><PageHeader title="Mijozlar" subtitle="Yangi do‘kon, bir martalik kirish ma’lumoti va qurilma ulash kodi." actions={<button className="btn btn-primary" onClick={()=>setAdding(value=>!value)}><Icon name="users"/>{adding?"Bekor qilish":"Yangi mijoz"}</button>}/>{adding?<Card className="employee-form"><form className="card-body" onSubmit={submit}><div className="form-grid"><label>Do‘kon yoki kompaniya nomi<input className="input" name="name" minLength={2} required/></label><label>Tarif<select className="select" name="plan" defaultValue="biznes"><option value="boshlangich">Boshlang‘ich</option><option value="biznes">Biznes</option></select></label><label>Telefon<input className="input" name="phone" inputMode="tel" placeholder="+998…"/></label><label>Manzil<input className="input" name="address"/></label><label>Obuna muddati<select className="select" name="months" defaultValue="1"><option value="1">1 oy</option><option value="3">3 oy</option><option value="6">6 oy</option><option value="12">12 oy</option></select></label></div><button className="btn btn-primary" disabled={busy}>{busy?"Yaratilmoqda…":"Mijoz va login yaratish"}</button></form></Card>:null}{error?<div className="alert-strip"><Icon name="bell"/><div><strong>Amal bajarilmadi:</strong> {error}</div></div>:null}{created?<Card className="credential-card"><div className="card-head"><div><h2>Kirish ma’lumoti tayyor</h2><p>Parol faqat shu safar ko‘rinadi — xavfsiz tarzda mijozga yuboring</p></div><Pill state="active">Yaratildi</Pill></div><div className="credential-grid"><div><span>Panel</span><b>{window.location.origin}/owner</b></div><div><span>Login</span><b>{created.username}</b></div><div><span>Bir martalik parol</span><b>{created.password}</b></div><div><span>Qurilma ulash kodi</span><b>{created.pairing_code}</b></div></div><div className="card-body"><button className="btn btn-primary" onClick={copyCredentials}>Hammasini nusxalash</button></div></Card>:null}<div className="section-gap"><SiteTable sites={sites} onCreate={()=>setAdding(true)}/></div></>;
}

function PaymentsPage() {
  const[items,setItems]=useState<AdminInvoice[]|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState("");
  const load=useCallback(()=>api<AdminInvoice[]>("/api/v1/admin/invoices","admin").then(data=>{setItems(data);setError("");}).catch(reason=>setError(reason instanceof Error?reason.message:"To‘lovlar olinmadi")),[]);
  useEffect(()=>{void load();},[load]);
  const approve=async(invoice:AdminInvoice)=>{if(!window.confirm(`#${invoice.id} hisobini qo‘lda to‘langan deb tasdiqlaysizmi? Obuna uzayadi.`))return;setBusy(invoice.id);setError("");try{await api(`/api/v1/admin/invoices/${encodeURIComponent(invoice.id)}/paid`,"admin",{method:"POST",body:JSON.stringify({provider:"manual",reference:null})});await load();}catch(reason){setError(reason instanceof Error?reason.message:"To‘lov tasdiqlanmadi");}finally{setBusy("");}};
  return <><PageHeader title="To‘lovlar" subtitle="Hisob-faktura va operator tasdig‘idagi real obuna jarayoni."/>{error?<div className="alert-strip"><Icon name="bell"/><div><strong>To‘lov bilan muammo:</strong> {error}</div></div>:null}<Card><div className="card-head"><div><h2>Hisob-fakturalar</h2><p>Tasdiqlash obuna muddatini avtomatik uzaytiradi</p></div></div>{items===null?<div className="card-body"><Skeleton height={180}/></div>:items.length?<div className="table-wrap"><table><thead><tr><th>Mijoz</th><th>Hisob</th><th>Muddat</th><th>Summa</th><th>Holat</th><th>Amal</th></tr></thead><tbody>{items.map(invoice=><tr key={invoice.id}><td><div className="table-title">{invoice.site_name||invoice.site_id}</div></td><td>#{invoice.id}</td><td>{invoice.months} oy</td><td>{formatMoney(invoice.amount_uzs)}</td><td><Pill state={invoice.state}>{invoice.state==="paid"?"To‘langan":invoice.state==="pending"?"Kutilmoqda":"Bekor"}</Pill></td><td>{invoice.state==="pending"?<button className="btn btn-primary" disabled={busy===invoice.id} onClick={()=>void approve(invoice)}>{busy===invoice.id?"Tasdiqlanmoqda…":"To‘lovni tasdiqlash"}</button>:invoice.provider||"—"}</td></tr>)}</tbody></table></div>:<EmptyState icon="invoice" title="Hisob-faktura yo‘q" detail="Mijoz hisob yaratgach u shu ro‘yxatda ko‘rinadi."/>}</Card></>;
}

function PlansPage() {
  const[data,setData]=useState<{price_book?:{label?:string;usd_rate_uzs?:number;base_fee_usd_cents?:number};features:Feature[]}|null>(null);const[error,setError]=useState("");
  useEffect(()=>{api<{price_book?:{label?:string;usd_rate_uzs?:number;base_fee_usd_cents?:number};features:Feature[]}>("/api/v1/admin/features","admin").then(setData).catch(reason=>setError(reason instanceof Error?reason.message:"Katalog olinmadi"));},[]);
  return <><PageHeader title="Tariflar" subtitle="Versiyalangan narx katalogi; qo‘lda yozilgan soxta qiymat ko‘rsatilmaydi."/>{error?<div className="alert-strip"><Icon name="bell"/>{error}</div>:null}{data?<><div className="metric-grid"><MetricCard label="Faol katalog" value={data.price_book?.label||"—"} note="Serverdagi nashr" icon="card"/><MetricCard label="AI funksiyalar" value={formatNumber(data.features.length)} note="Katalogdagi imkoniyatlar" icon="pulse"/><MetricCard label="USD kursi" value={formatMoney(data.price_book?.usd_rate_uzs)} note="Hisoblash manbasi" icon="chart"/><MetricCard label="Platforma bazasi" value={data.price_book?.base_fee_usd_cents==null?"—":`$${(data.price_book.base_fee_usd_cents/100).toFixed(0)}`} note="Oylik bazaviy haq" icon="server"/></div><Card><div className="card-head"><div><h2>Funksiyalar katalogi</h2><p>Bir kamera uchun oylik qiymat</p></div></div><div className="table-wrap"><table><thead><tr><th>Funksiya</th><th>Tur</th><th>Mijoz narxi</th><th>Ichki qiymat</th></tr></thead><tbody>{data.features.map(feature=><tr key={feature.code}><td><div className="table-title">{feature.name}</div><div className="table-sub">{feature.code}</div></td><td>{feature.category}</td><td>${(feature.monthly_usd_cents/100).toFixed(2)}</td><td>${(feature.cost_usd_cents/100).toFixed(2)}</td></tr>)}</tbody></table></div></Card></>:<Card><div className="card-body"><Skeleton height={190}/></div></Card>}</>;
}

function EventsPage({sites}:{sites:Site[]}) {
  const[events,setEvents]=useState<AdminEvent[]|null>(null);const[siteId,setSiteId]=useState("");const[error,setError]=useState("");
  useEffect(()=>{const query=siteId?`?site_id=${encodeURIComponent(siteId)}`:"";api<{events:AdminEvent[]}>(`/api/v1/admin/events${query}`,"admin").then(data=>{setEvents(data.events);setError("");}).catch(reason=>setError(reason instanceof Error?reason.message:"Hodisalar olinmadi"));},[siteId]);
  return <><PageHeader title="AI hodisalar" subtitle="Filiallar bo‘yicha anonim oqim va xavfsizlik voqealari." actions={<select className="select" value={siteId} onChange={event=>setSiteId(event.target.value)}><option value="">Barcha filiallar</option>{sites.map(site=><option key={site.id} value={site.id}>{site.name}</option>)}</select>}/>{error?<div className="alert-strip"><Icon name="bell"/>{error}</div>:null}<Card>{events===null?<div className="card-body"><Skeleton height={190}/></div>:events.length?<div className="event-list">{events.map((item,index)=><div className="event-row" key={item.event_id||item.id||index}><div className="event-name"><div className="metric-icon tone-blue" style={{position:"static",width:34,height:34}}><Icon name="pulse" size={17}/></div><div><b>{item.label||item.event_type}</b><small>{item.site_name||"—"} · {item.camera_id||"Tizim"}</small></div></div><span className="list-value">{item.occurred_at?new Date(item.occurred_at).toLocaleString("uz-UZ"):"—"}</span></div>)}</div>:<EmptyState icon="pulse" title="Hodisa yo‘q" detail="Qurilmalar AI hodisa yuborgach real voqealar shu yerda ko‘rinadi."/>}</Card></>;
}

function RolesPage() {
  const[accounts,setAccounts]=useState<Account[]|null>(null);const[error,setError]=useState("");
  useEffect(()=>{api<{accounts:Account[]}>("/api/v1/admin/accounts","admin").then(data=>setAccounts(data.accounts)).catch(reason=>setError(reason instanceof Error?reason.message:"Akkauntlar olinmadi"));},[]);
  return <><PageHeader title="Rollar" subtitle="Admin, o‘rnatuvchi va mijoz akkauntlarining haqiqiy ruxsat holati."/>{error?<div className="alert-strip"><Icon name="bell"/>{error}</div>:null}<Card>{accounts===null?<div className="card-body"><Skeleton height={180}/></div>:accounts.length?<div className="table-wrap"><table><thead><tr><th>Foydalanuvchi</th><th>Login</th><th>Rol</th><th>Holat</th><th>Filial</th></tr></thead><tbody>{accounts.map(account=><tr key={account.id}><td><div className="table-title">{account.full_name||account.company||"—"}</div></td><td>{account.username}</td><td>{account.role}</td><td><Pill state={account.status}>{account.status}</Pill></td><td>{account.site_id||"Platforma"}</td></tr>)}</tbody></table></div>:<EmptyState icon="shield" title="Akkaunt yo‘q" detail="Akkaunt yaratilgach rol va holati shu yerda ko‘rinadi."/>}</Card></>;
}

function SettingsPage() {
  const[data,setData]=useState<{items?:ReadinessItem[]}|null>(null);const[error,setError]=useState("");
  useEffect(()=>{api<{items?:ReadinessItem[]}>("/api/v1/admin/readiness","admin").then(setData).catch(reason=>setError(reason instanceof Error?reason.message:"Readiness olinmadi"));},[]);
  const items=data?.items||[];
  return <><PageHeader title="Sozlamalar" subtitle="Ishlab chiqarish integratsiyalari va xavfsizlik tayyorligi."/>{error?<div className="alert-strip"><Icon name="bell"/>{error}</div>:null}<Card><div className="card-head"><div><h2>Production readiness</h2><p>Yashirilmagan real muhit tekshiruvlari</p></div></div>{data?<div className="health-list">{items.map(item=><div className="health-row" key={item.key}><div className="health-name"><span className={`status-dot status-${item.ok?"online":item.required?"offline":"stale"}`}/><div><b>{item.label}</b><small>{item.reasons?.join(" · ")|| (item.required?"Majburiy tekshiruv":"Ixtiyoriy tekshiruv")}</small></div></div><Pill state={item.ok?"active":item.required?"failed":"pending"}>{item.ok?"Tayyor":item.required?"Tayyor emas":"Ixtiyoriy"}</Pill></div>)}</div>:<div className="card-body"><Skeleton height={190}/></div>}</Card></>;
}

function GenericAdmin({id,data,onRefresh}:{id:string;data:AdminDashboard;onRefresh:()=>Promise<void>}) {
  if(id==="customers") return <CustomersPage sites={data.sites} onRefresh={onRefresh}/>;
  if(id==="branches") return <><PageHeader title="Filiallar" subtitle="Obuna va tizim holatini bitta ro‘yxatdan boshqaring."/><SiteTable sites={data.sites}/></>;
  if(id==="devices"||id==="monitoring") return <><PageHeader title={id==="devices"?"Qurilmalar":"Monitoring"} subtitle="Sotqin agentlari va haqiqiy resurs ko‘rsatkichlari."/><Telemetry items={data.telemetry}/></>;
  if(id==="cameras") return <><PageHeader title="Kameralar" subtitle="Filiallar bo‘yicha ishlayotgan va e’tibor talab qiladigan kameralar."/><div className="metric-grid">{data.sites.map(site=><MetricCard key={site.id} label={site.name} value={`${formatNumber(site.cameras_active)} / ${formatNumber(site.cameras_expected)}`} note={site.connection||"—"} icon="camera" tone={(site.cameras_active||0)>=(site.cameras_expected||1)?"green":"red"}/>)}</div></>;
  if(id==="plans") return <PlansPage/>;
  if(id==="payments") return <PaymentsPage/>;
  if(id==="events") return <EventsPage sites={data.sites}/>;
  if(id==="roles") return <RolesPage/>;
  if(id==="settings") return <SettingsPage/>;
  return <><PageHeader title="Bo‘lim" subtitle="Operatsion boshqaruv."/><Card><EmptyState icon="settings" title="Ma’lumot yo‘q" detail="Haqiqiy ma’lumot kelgach shu yerda ko‘rinadi."/></Card></>;
}

function AdminApp(){const[authenticated,setAuthenticated]=useState(()=>Boolean(tokenFor("admin")));const[active,setActive]=useState("overview");const[range,setRange]=useState("7d");const[busy,setBusy]=useState(false);const[loginError,setLoginError]=useState("");const[drawer,setDrawer]=useState(false);const{data,loading,error,refresh}=useAdminDashboard(authenticated,range);const submit=async(username:string,password:string)=>{setBusy(true);setLoginError("");try{await login(username,password,"admin");setAuthenticated(true);}catch(reason){setLoginError(reason instanceof Error?reason.message:"Kirish amalga oshmadi");}finally{setBusy(false);}};const logout=()=>{clearToken("admin");setAuthenticated(false);};const navigate=(id:string)=>{if(id==="more")setDrawer(true);else{setActive(id);setDrawer(false);window.scrollTo({top:0,behavior:"smooth"});}};const offline=useMemo(()=>data?.stats.offline||0,[data?.stats.offline]);if(!authenticated)return <LoginScreen kind="admin" onSubmit={submit} busy={busy} error={loginError}/>;if(loading||!data)return <div className="login-page"><section className="login-visual"><Logo/><div><span className="eyebrow">ADMIN PANEL</span><h1>Platforma holati olinmoqda.</h1></div></section><section className="login-panel"><div style={{width:"min(390px,100%)"}}><Skeleton height={60}/><div style={{height:14}}/><Skeleton height={180}/></div></section></div>;return <AppShell kind="admin" nav={NAV} active={active} onNavigate={navigate} title="Chaqimchi Cloud" subtitle={`${offline?`${offline} ta oflayn tizim`:"Barcha tizimlar nazoratda"} · ${new Date(data.updated_at).toLocaleTimeString("uz-UZ",{hour:"2-digit",minute:"2-digit"})}`} onLogout={logout} headerActions={<><select className="select" value={range} onChange={event=>setRange(event.target.value)} aria-label="Davr"><option value="7d">7 kun</option><option value="30d">30 kun</option></select><button className="btn btn-icon" onClick={()=>void refresh()} aria-label="Yangilash"><Icon name="pulse"/></button></>}>{error?<div className="alert-strip"><Icon name="bell"/><div><strong>Yangilashda muammo:</strong> {error}. Oxirgi ma’lumot ko‘rsatilmoqda.</div></div>:null}{active==="overview"?<Overview data={data} onNavigate={navigate}/>:<GenericAdmin id={active} data={data} onRefresh={refresh}/>} {drawer?<div className="drawer-backdrop" onClick={()=>setDrawer(false)}><aside className="drawer" onClick={event=>event.stopPropagation()}><div className="drawer-head"><Logo/><button className="btn btn-icon" onClick={()=>setDrawer(false)}><Icon name="close"/></button></div><nav>{NAV.map(item=><button key={item.id} className={active===item.id?"active":""} onClick={()=>navigate(item.id)}><Icon name={item.icon}/>{item.label}</button>)}</nav></aside></div>:null}</AppShell>;}

createRoot(document.getElementById("root")!).render(<StrictMode><AdminApp/></StrictMode>);
